### ISSUE TITLE
[1.14.4] Error on client startup

### ISSUE THREAD

**Issue by MBoberski** [Cadiboo/NoCubes#62] opened 2019-10-11 11:20 UTC
I'm starting to learn about mod creation so I checkot: https://github.com/McJty/YouTubeModding14 and runt it in IntelliJ. I worked but when I try to add NoCubes-1.14.4-0.4.0-pre7.jar and OptiFine_1.14.4_HD_U_F3.jar into: run\mods dir, I get:

[crash-2019-09-14_17.32.30-client.txt](https://github.com/Cadiboo/NoCubes/files/3717214/crash-2019-09-14_17.32.30-client.txt)

after: gradlew clientRun.
Any idea why?

**Comment by Cadiboo** [comment] 2019-10-12 00:21
Don't use the `runClient` command, use your run configs.
Your issue appears to be called by enderio.
```
java.lang.NullPointerException: Houston we have a problem: 'Item item_owl_egg is unexpectedly missing'. Please report that on our bugtracker unless you are using some old version. Thank you.
	at com.enderio.core.common.util.NullHelper.notnull(NullHelper.java:47)
```
I'm guessing that there are lots of issues happening with core mods. For one, OptiFine_1.14.4_HD_U_F3 isn't able to be run by Forge. Please share your `debug.log` as it will contain more info.
Feel free to discus this [on discord](https://cadiboo.github.io/projects/nocubes/discord/).

**Comment by MBoberski** [comment] 2019-10-12 22:13
![image](https://user-images.githubusercontent.com/2800036/66708245-d434b700-ed4d-11e9-9d49-ddcdc05b3a58.png)
and
[debug.log](https://github.com/Cadiboo/NoCubes/files/3721219/debug.log)
and
[build.gradle.txt](https://github.com/Cadiboo/NoCubes/files/3721220/build.gradle.txt)

Now I used: NoCubes-1.14.4-0.4.0-pre7.jar and preview_OptiFine_1.14.4_HD_U_F4_pre9.jar

**Comment by Cadiboo** [comment] 2019-10-12 22:35
Your log is filled with `[optifine.OptiFineTransformer:getOptiFineResourcePatched]: java.io.IOException: Base resource not found: obfuscatedClassName.class`. OptiFine needs special handling to be run in a development environment. This crash is caused by NoCubes loading OptiFine's `Config` class and the game crashing due to the `Config` class referencing the srg-named method `Minecraft.func_71410_x()` (`Minecraft.getInstance()`). OptiFine needs to be deobfuscated to allow it to run in a development environment. This can be done with my [OptiFineDeobf](https://github.com/Cadiboo/OptiFineDeobf) or with Barkeks2x's [OptiFineDevTweaker](https://github.com/OpenCubicChunks/OptiFineDevTweaker). You may also need a deobf version of NoCubes.

**Comment by MBoberski** [comment] 2019-10-12 22:57
Can you provide me with NoCubes one?

**Comment by MBoberski** [comment] 2019-10-12 23:07
I added OptiFineDeobf-1.0.0-all.jar, it runed and stuck on 9% new world creation.

![image](https://user-images.githubusercontent.com/2800036/66708736-bec38b00-ed55-11e9-8335-fb236b4f4bbe.png)

**Comment by Cadiboo** [comment] 2019-10-13 01:49
> I added OptiFineDeobf-1.0.0-all.jar

OptiFineDeobf is a stand-alone tool for deobfuscating OptiFine. I’ll get a dev version of NoCubes for you as soon as I get home

**Comment by MBoberski** [comment] 2019-10-13 11:51
Ok no I use OptiFine_1.14.4_HD_U_F4_pre9_MOD-deobf.jar (deobfuscating OptiFine) and NoCubes-1.14.4-0.4.0-pre7.jar. On world creation it stucks on 0%, and spamming error below:

```
[13:46:36] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Chunk source main thread executor for minecraft:overworld
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: net.minecraft.util.math.shapes.VoxelShapes.func_197881_a(Lnet/minecraft/util/math/AxisAlignedBB;)Lnet/minecraft/util/math/shapes/VoxelShape;
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_221] {}
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_221] {}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:961) ~[?:1.8.0_221] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_221] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_221] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.driveOne(SourceFile:83) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.driveWhile(SourceFile:123) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:91) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_221] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_221] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_221] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_221] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_221] {}
Caused by: java.lang.NoSuchMethodError: net.minecraft.util.math.shapes.VoxelShapes.func_197881_a(Lnet/minecraft/util/math/AxisAlignedBB;)Lnet/minecraft/util/math/shapes/VoxelShape;
	at io.github.cadiboo.nocubes.collision.CollisionHandler.getVanillaCollisions(CollisionHandler.java:300) ~[?:1.14.4-0.4.0-pre7] {re:classloading}
	at io.github.cadiboo.nocubes.collision.CollisionHandler.getCollisionShapes(CollisionHandler.java:73) ~[?:1.14.4-0.4.0-pre7] {re:classloading}
	at io.github.cadiboo.nocubes.hooks.Hooks.getCollisionShapes(Hooks.java:90) ~[?:1.14.4-0.4.0-pre7] {re:classloading}
	at net.minecraft.world.IWorldReader.getCollisionShapes(IWorldReader.java:141) ~[?:?] {re:classloading,xf:fml:nocubes:IWorldReader#getCollisionShapes}
	at net.minecraft.world.IWorldReader.getCollisionShapes(IWorldReader.java:131) ~[?:?] {re:classloading,xf:fml:nocubes:IWorldReader#getCollisionShapes}
	at net.minecraft.world.IWorldReader.isCollisionBoxesEmpty(IWorldReader.java:123) ~[?:?] {re:classloading,xf:fml:nocubes:IWorldReader#getCollisionShapes}
	at net.minecraft.world.IWorldReader.areCollisionShapesEmpty(IWorldReader.java:111) ~[?:?] {re:classloading,xf:fml:nocubes:IWorldReader#getCollisionShapes}
	at net.minecraft.world.spawner.WorldEntitySpawner.performWorldGenSpawning(WorldEntitySpawner.java:245) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.OverworldChunkGenerator.spawnMobs(SourceFile:55) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$12(ChunkStatus.java:87) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus$ISelectiveWorker.doWork(ChunkStatus.java:238) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:196) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ChunkManager.lambda$null$17(ChunkManager.java:509) ~[?:?] {re:classloading}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-2.0.24.jar:?] {}
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$19(ChunkManager.java:507) ~[?:?] {re:classloading}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_221] {}
	... 11 more
```

**Comment by MBoberski** [comment] 2019-10-13 17:40
Ok I sorted it out. I think... :P Do your mod works with shaders? Example: http://shadersmods.com/sildurs-shaders-mod/

**Comment by Cadiboo** [comment] 2019-10-14 01:50
> Ok I sorted it out. I think... :P Do your mod works with shaders? Example: http://shadersmods.com/sildurs-shaders-mod/

Yes

**Comment by MBoberski** [comment] 2019-10-15 11:14
I tested it and I have block insted of you no cubes.

**Comment by Cadiboo** [comment] 2019-10-16 03:45
Is OptiFine installed? If so please refer to #61

**Comment by Cadiboo** [comment] 2019-10-20 13:07
#61 has been fixed, so this should be fixed too.

**Closed by Cadiboo** 2019-10-20 13:07 UTC
Labels: 1.14.4
