### ISSUE TITLE
crash with my modpack forge 47.2.16 1.20.1 nocube version 0.5.0

### ISSUE THREAD

**Issue by Thunderrock424242** [Cadiboo/NoCubes#109] opened 2023-12-15 00:18 UTC
crash log is here 
[latest.log](https://github.com/Cadiboo/NoCubes/files/13679500/latest.log)

**Comment by Cadiboo** [comment] 2023-12-15 19:08
Duplicate of #88, Rubidium is not currently supported.

**Closed by Cadiboo** 2023-12-15 19:08 UTC
