### ISSUE TITLE
Crashing at startup

### ISSUE THREAD

**Issue by drago87** [Cadiboo/NoCubes#59] opened 2019-09-14 15:50 UTC
When adding to a modpack i'm working on the game crashes

OpenEye Crash report
https://openeye.openmods.info/crashes/761a73e8b69462d73d6818944c937b62

Vanilla Crash report
[crash-2019-09-14_17.32.30-client.txt](https://github.com/Cadiboo/NoCubes/files/3612876/crash-2019-09-14_17.32.30-client.txt)

I will post this at the Ender IO github to as that is the reported mod by OpenEye

**Comment by drago87** [comment] 2019-09-14 17:57
The Ender IO post linked me to
https://github.com/MinecraftForge/MinecraftForge/issues/6148

**Comment by Cadiboo** [comment] 2019-09-15 21:51
Thanks, I'll look into this. Can you please post your `debug.log`?
[MinecraftForge/MinecraftForge#6148](https://github.com/MinecraftForge/MinecraftForge/issues/6148) is probably unrelated as it is for 1.13+ and this is on 1.12.2.

**Comment by drago87** [comment] 2019-09-17 13:49
nothing seams intreasting in the log but here it is
[debug.log](https://github.com/Cadiboo/NoCubes/files/3621651/debug.log)

**Comment by Cadiboo** [comment] 2019-09-18 23:07
Where did you get that debug log from? That doesn't seem to be a log that was generated by Minecraft or even a Java program at all. Your `debug.log` should be in `.minecraft/logs/debug.log`

**Comment by drago87** [comment] 2019-09-20 14:22
i got it from the modpack folder. using the twitch launcer to make the pack
Here is a debug log i found in the "Twitch/Minecraft/Install" folder
[debug.log](https://github.com/Cadiboo/NoCubes/files/3636348/debug.log)

**Comment by Cadiboo** [comment] 2019-10-20 13:08
Sorry for the late reply, that also doesn't seem to be a log that was generated by Minecraft.

**Comment by Rocketblaster247** [comment] 2020-02-08 14:42
This happens to me when only running Optifine and NoCubes.

**Comment by Cadiboo** [comment] 2020-02-08 14:59
How do you know you’ve got the same issue? The original issue has an open eye log and a vanilla crash report that both show EnderIO crashing. The other two logs are not minecraft logs and the linked issue is for a different minecraft version. If you have an issue/bug report with NoCubes make your own issue.

Closing this because it’s been close to half a year without any evidence that this crash is caused by NoCubes.

**Closed by Cadiboo** 2020-02-08 14:59 UTC
Labels: 1.12.2, bug
