### ISSUE TITLE
Modded Block Render Bugs

### ISSUE THREAD

**Issue by WenXin20** [Cadiboo/NoCubes#27] opened 2019-03-05 02:32 UTC
Forge v14.23.5.2810-1.12.2
No Cubes v0.2.6-pre1

I noticed that some mod blocks, when added to the config, display oddly. Are any of these able to be fixed?
- [Mubble](https://minecraft.curseforge.com/projects/mubble) unstable stone displays as normal Minecraft stone
- [Underground Biomes's](https://minecraft.curseforge.com/projects/underground-biomes) ores doesn't keep its ore texture, but displays as the modded base stone.
- [Treasure 2's](https://minecraft.curseforge.com/projects/treasure2) ores do the same thing. I think they both use an overlay texture.
- [Dust's](https://minecraft.curseforge.com/projects/dust) ores render as stretched out stone when added, though since it uses a 3D model, I'm not sure anything can be done.
- Puddles from the [Puddles](https://minecraft.curseforge.com/projects/puddles) mod can let you see into the world. Any blocks with transparency seems to do that.
- [Dynamic Trees'](https://minecraft.curseforge.com/projects/dynamictrees) rooty sand and dirt display a purple and black texture.

Mubble Unstable Stone:
Before & After:
![before-after unstable stone](https://user-images.githubusercontent.com/12000593/53776212-f95d6f00-3eba-11e9-9d34-1005c1a76aa8.png)

Underground Biomes' Ores:
![2019-03-04_18 55 10](https://user-images.githubusercontent.com/12000593/53775240-59521680-3eb7-11e9-8a9e-958bd180affe.png)

Treasure 2's Ores:
![2019-03-04_11 41 26](https://user-images.githubusercontent.com/12000593/53776336-5d803300-3ebb-11e9-9501-dc1f021eda87.png)

Puddle from the Puddles mod:
![2019-03-04_17 30 32](https://user-images.githubusercontent.com/12000593/53775239-59521680-3eb7-11e9-8907-0a542b2ac173.png)

Dynamic Trees Rooty Sand:
![2019-03-03_13 52 20](https://user-images.githubusercontent.com/12000593/53775319-b77ef980-3eb7-11e9-9a7d-17e0a86e8466.png)

**Comment by Cadiboo** [comment] 2019-03-05 03:19
I don’t support having more than 1 texture (i.e. overlays) for a block yet, this will be fixed soon and at the same time as emissive quad support is added. I have no clue about dynamic trees roots. My assumption is that they’re using a TESR to render their roots, rather than a custom baked model.
A TESR (TileEntity Special Renderer) is a renderer that directly renders everything each frame. A BakedModel is a model that is re-rendered by the minecraft chunk renderer every time a chunk changes.
BakedModels simply provide a list of faces and textures, which NoCubes reads and renders itself. A TESR re-renders every frame so it can be much more dynamic than baked models. TESRs are also easier to code than a custom baked model, but are more performance intensive. Because a TESR renders everything itself, the block it’s rendering usually returns a missing texture/no texture from its baked model, as the baked model is normally never used. I’ll look at the dynamic trees code, but I think if I’m right and they are using a TESR, it’s a problem on their side.

**Comment by WenXin20** [comment] 2019-03-05 03:33
Ok, thanks. I can report it there if that's the case.

**Comment by Jdewi12** [comment] 2019-03-05 03:34
I don't think it's a bug on their side, rather just something that is unsupported by NoCubes (if I'm understanding right)

**Comment by Cadiboo** [comment] 2019-03-05 03:35
Its not a bug per say, I think they're just doing stuff in an insupportable and needlessly performance intensive way. I haven't looked at their code yet though

**Comment by jredfox** [comment] 2019-04-20 06:35
the normal rendering is due to non auto detection and your configuration settings not really no cubes itself. this also could be the same with liquid. As for missing textures and improper colors there might be an issue there but, only report one issue per report 99% of the time it's the proper way to do it

**Comment by Cadiboo** [comment] 2019-04-20 08:36
1 is caused by NoCubes not rendering all the parts of the model (will be fixed soon:tm:)
2 probably the same as 1
3 possibly the same as 1
4 the same as 1
5 no clue wtf is wrong or what Dynamic Trees is doing, but I added explicit support for their rooty dirt and now everything works
> non auto detection

Coming soon:tm:
> only report one issue per report 99% of the time it's the proper way to do it

^

**Comment by Cadiboo** [comment] 2019-04-25 07:26
Should be fixed in the latest pre-release

**Closed by Cadiboo** 2019-04-25 07:26 UTC
